name: Notadd Markdown 编辑器
identification: notadd/ext-markdown
description:
author:
    - Notadd
    - notadd@ibenchu.com
provider: Notadd\Markdown\Extension
publishes:
    assets/extensions/notadd/markdown: resources/mixes